### ISSUE TITLE
Recommendations for a clean distribution

### ISSUE THREAD

**Issue by ftadel** [MIA-iEEG/mia#23]
- Remove all the `.DS_Store` coming from your MacOS (add it to your .gitignore)
- Remove all the .asv files
- external/altmany: do you need all of it?
- external/eeglab: move all these functions in a `private` subfolder of the functions where you need it - otherwise it would conflict with any other EEGLAB installation once added to the Matlab path.
- external/*.m: same problem, many other toolboxes might have functions named "quantile.m" or "tinv.m", causing nasty hidden bugs
- utils: Remove all the functions coming from Brainstorm - duplicating them is really looking for trouble. If you want to have a stand-alone MIA running without Brainstorm, move the Brainstorm functions to a `standalone` folder, that you add to the path only when Brainstorm is not running.
- In general: adding a `mia_` prefix to all the function names would help avoiding conflicts.

**Comment by annesodub** [comment]
Thank you Francois, I will address these issues as soon as I can (most probably after [CuttingEEG](https://cuttingeeg2021.org/))

**Comment by ftadel** [comment]
> What do you mean by "Remove all the .asv files"? I do not see any .asv files..

Example:  https://github.com/MIA-iEEG/mia/blob/master/GUI/ganalysis_gui.asv

> Remove all the .DS_Store coming from your MacOS (add it to your .gitignore)

They are still there, example : https://github.com/MIA-iEEG/mia/blob/master/.DS_Store
Delete all these files AND add that to your .gitignore.

**Comment by annesodub** [comment]
OK, it is fixed now! ( @ftadel : would you please confirm?)

**Comment by ftadel** [comment]
Looks good!

One last comment: The two functions `sort_nat.m` and `newid.m` were not written by you, they might fit better in the `external` folder.

**Comment by annesodub** [comment]
All done! Thank you Francois.
