### ISSUE TITLE
Provide a Brainstorm anatomical labelling table converter

### ISSUE THREAD

**Issue by annesodub** [MIA-iEEG/mia#27]
Write a function to convert the Brainstorm SEEG/ECOG labeling table into a MIA compatible format.

**Comment by annesodub** [comment]
Hi Shuai, thank you for asking. 

No I meant a function that converts Brainstorm labeling table (New feature in Brainstorm), and which looks like this : 

![image](https://user-images.githubusercontent.com/7487059/137891067-50ea7e4b-dc6c-448a-a766-6b1bf595fd04.png)
(from the very end of the page : https://neuroimage.usc.edu/brainstorm/Tutorials/ECoG)

to a MIA table that looks like this : 

![image](https://user-images.githubusercontent.com/7487059/137891192-655173bf-1df8-4034-ae48-59dc1e40bfd3.png)

This function would have to have the name of the chosen atlas as an input argument (e.g. 'ASEG' or 'Destrieux' or else). It would produce a MIA_labelling table with the name of the atlas in the filename (something like MIA_labelling_<atlas>).

**Comment by ws1011001** [comment]
P.S. This function (**brainstorm3/toolbox/io/export_channel_atlas.m**) generates the anatomical labeling (iEEG) table.

**Comment by annesodub** [comment]
This is done in https://github.com/MIA-iEEG/mia/pull/55#issue-1114857176

MIA now reads the iEEG tsv table. (mia_read_loc_tsv_table)

**Comment by annesodub** [comment]
@ws1011001 : do you have a chance to test this?

**Comment by ws1011001** [comment]
> 

Sorry I just see this message. Sure, I will test it.
