### ISSUE TITLE
compute_frequencies missing

### ISSUE THREAD

**Issue by DanielJanko** [MIA-iEEG/mia#75]
Hello,

I downloaded the archive and got MIA up and running. However, when I try to run the frequency command to apply wavelet, I get the following error
<img width="611" alt="Screenshot 2022-07-21 at 11 30 20" src="https://user-images.githubusercontent.com/96259676/180180780-8a4a244b-1368-40e5-88f8-df65ff006784.png">

To me, it seems like I am missing the compute_frequencies script. I checked the downloaded files and I can't find it anywhere.

What would you suggest I do?

Thank you for your help!

Regards,
Daniel

**Comment by annesodub** [comment]
Hi Daniel, 

I am sorry I missed your post.

compute_frequencies is a (local) function located of mia.m (line 892). It should not prevent you from running a TF extraction.

Sorry for the late answer.
