### ISSUE TITLE
mia_stats_permutations_rois.m is missing

### ISSUE THREAD

**Issue by yangping-1222** [MIA-iEEG/mia#76]
dear author,

when I run the mia_script_example_contrast_conditions, I found the file (mia_stats_permutations_rois.m) is missing. Could you please share this script?

Thanks
ping

**Comment by annesodub** [comment]
Dear Ping,
Thank you for your interest. Sorry about the missing file. I just added it to the repository. 
Please do not hesitate to get back to me with any question! 
Best,

**Comment by yangping-1222** [comment]
Dear Anne,
Thanks for sharing. Could you also provide the compute_ttest2distrib.m. Thanks again.
Ping

**Comment by annesodub** [comment]
Just added the file compute_ttest2distrib.m and another one (mia)tdcf) also required.

**Comment by yangping-1222** [comment]
Anne,
Thanks so much
I found the [tstat df] = ttest2_cell({ squeeze(dc1(contactidx,:,:)) squeeze(dc2(contactidx,:,:)) }); in the mia_compute_ttest2distrib.m
Should I run this line? But, the functions ttest2_cell and ft_fdr are not found.

Ping

**Comment by annesodub** [comment]
I add the missing functions (plus: renamed them and updated the function calls).

**Comment by yangping-1222** [comment]
Anne,
I have made some changes to the code, but I do not know if it is correct. 

In the mia_rois2pvalues.m 
"pv(ss) = length(find(Y>seg(ss)))/Fs;" changes to "pv(ss) = length(find(Y>seg(ss)))/length(croi.dur);"
The length(croi.dur) equals the number of permutations.

In the mia_display_rois_conditions_fdr.m
I moved the following two-line code
"seg_sumtp = seg_sumt(1:length([allroi.onsetpvalp]));
seg_sumtn = seg_sumt(length([allroi.onsetpvalp])+1:end);"
to the back of 
"% Get the boolean vector of clusters that were on/off back in the whole tw
twpval(find(twpval)) = seg_sumt ; seg_sumt = twpval ; "

Can you check these? Thanks. :)
Ping

**Comment by annesodub** [comment]
Ping,

> In the mia_rois2pvalues.m
> "pv(ss) = length(find(Y>seg(ss)))/Fs;" changes to "pv(ss) = length(find(Y>seg(ss)))/length(croi.dur);"
> The length(croi.dur) equals the number of permutations.

This line transforms a number of samples ( length(find(Y>seg(ss)))) into millisecond by dividing by the sampling rate (Fs). So I do not agree with this modification. 

> In the mia_display_rois_conditions_fdr.m
> I moved the following two-line code
> "seg_sumtp = seg_sumt(1:length([allroi.onsetpvalp]));
> seg_sumtn = seg_sumt(length([allroi.onsetpvalp])+1:end);"
> to the back of
> "% Get the boolean vector of clusters that were on/off back in the whole tw
> twpval(find(twpval)) = seg_sumt ; seg_sumt = twpval ; "

Why this modification?

**Comment by yangping-1222** [comment]
Anne,
Thanks for your reply. If I don't make the second modification, the increase of ctsumtn variable will exceed the dimension of the seg_sumtn variable. The code of "if seg_sumtn(ctsumtn)==1" will report an error.

ping

**Comment by yangping-1222** [comment]
Anne,
Sorry to bother you again. I don't know the permutation test very well. 
In the mia_rois2pvalues.m,
"    [Y,I] = sort(croi.dur);
    pv = [] ;
    Fs = 1 /(croi.t(2) - croi.t(1));
        
    for ss=1:length(seg) 
        pv(ss) = length(find(Y>seg(ss)))/Fs;% 
    end"
If I had run 2000 permutations, then I got 2000 values saved in croi.dur. This 2000 values were sorted in Y. When I want to get the p value for each seg, which is pv(ss), should I divide by Fs (1000) or the number of permutations (2000)?
Thanks again.
Ping
