### ISSUE TITLE
Brainstorm Export to MIA database not available

### ISSUE THREAD

**Issue by avolfart** [MIA-iEEG/mia#90]
Hi, 

I would like to export my data from Brainstorm to MIA but the function described in your 2022 paper (File > Export to MIA database) does not appear. I have checked that the MIA plugin is correctly installed and it is. 
I use MATLAB 2023b (also tried with 2019b without success) and Brainstorm latest version (06-Feb-2024). Is MIA still supported on  recent Brainstorm versions? Could the error come from somewhere else? 

Best,
Angelique

**Comment by annesodub** [comment]
Hi Angélique, 

Thank you for reaching out! 

Unfortunately I could not reproduce the issue with Brainstorm version 06-Feb-2024 and Matlab 2023b (see snapshot below) 

<img width="674" alt="image" src="https://github.com/MIA-iEEG/mia/assets/7487059/d222835a-d01b-484b-ab80-073e5d0209ac">


Could you please make sure the MIA plugin is installed? From Brainstorm main interface in the menu Plugins-> SEEG -> mia (a green dot should appear and the content should display the same as the snapshot below) 

<img width="434" alt="image" src="https://github.com/MIA-iEEG/mia/assets/7487059/026f2a48-a7aa-4c37-be97-b11a3e4345b4">


Please let me know if this helps, or if we need to further investigate the issue. 


Best,
AnneSo

**Comment by avolfart** [comment]
Hi AnneSo, 

Thank you for your quick reply. 
I did check and the mia plugin seems to be correctly installed: 
![image](https://github.com/MIA-iEEG/mia/assets/119902277/a2af9a8c-51ca-46ed-bd1d-b91610520ee9)

But the option just does not appear in the pipeline editor:
![image](https://github.com/MIA-iEEG/mia/assets/119902277/b73f484d-0800-44d3-b52f-13b3c5fe9263)

However I did notice that this MAC computer I work on was updated recently and this message shows up in the Matlab window: 
![image](https://github.com/MIA-iEEG/mia/assets/119902277/0356ee2d-b163-441b-b9cb-0e3e3f26eec8)

Do you think MIA might be one of the plugins that are not supported yet on Apple silicon?

**Comment by annesodub** [comment]
I also have a Mac computer with Apple Silicon (M1) the OS is Monterey and I do not have the Warning message. @rcassani : do you have an idea of the problem here?

**Comment by rcassani** [comment]
The problems seems to be that the MIA plugin was not installed by Brainstorm, but it manually by the user. Thus the "Custom install" legend in the menu.

@avolfart, check the Matlab Command Window when Brainstorm starts it will indicate that the path to the custom installations of the MIA plugin. Something like:

`BST> Plugin mia: /home/rcassani/Desktop/mia-master/bst_plugin`

If you want Brainstorm to handle the installation of MIA, and updates. Restart Matlab, and edit the Path to remove the path of the custom installation of MIA.

Then start Brainstorm, the legend indicating the path of the MIA should have disappeared.
Processed to install the MIA plugin from the Brainstorm GUI.

---
@annesodub, could it be that you installed the "Matlab23b (Intel processor)"? That warning will show at Brainstorm start only if the version "Matlab23b (Apple silicon)" (or later versions) are installed.

**Comment by annesodub** [comment]
@rcassani : thank you very much for your help. 

Oh yes, I think I installed the intel processor one... (see snapshot below showing "maci64")

Do you anticipate any issue using this version (in particular for the hands-on tutorial that I will give at the [WIRED conference](https://wired-icm.org/)?

<img width="412" alt="image" src="https://github.com/MIA-iEEG/mia/assets/7487059/d8aedaf1-ac89-4569-9e75-f11316d4342e">

Do you anticipate any issue using this version (in particular for the hands-on tutorial that I will give at the [WIRED conference](https://wired-icm.org/)?

**Comment by rcassani** [comment]
No, there isn't any issue.

**Comment by avolfart** [comment]
Hi both, 
It seems I never received the notifications from GitHub, only @annesodub's message closing the post, sorry about that. 
I tried doing what @rcassani recommended (installation through Brainstorm GUI directly) and it works now, the option to export data to MIA is now available!
Thank you very much to both of you for your help.
