### ISSUE TITLE
MIA displaying varying sampling rate and error while creating study

### ISSUE THREAD

**Issue by avolfart** [MIA-iEEG/mia#91]
Hi, 

I have an issue where the "Fs" column in MIA that is supposed to list the sampling rate of each patient's file returns either 1000 or 1001Hz although all data is sampled at 1000Hz. 
See screenshot below:
![image](https://github.com/MIA-iEEG/mia/assets/119902277/0cee856c-af65-42b4-8e85-f5d33d2c5dff)

Before importing to MIA, data for 6 patients (name starting with "EMU") was resampled from 2048 to 1000Hz and then epoched (from -1s to 3s around trigger). 
All patients whose name start with "Subj" were natively sampled at 1000Hz and also epoched before importing to MIA. 
You can see on the screenshot that Subj3 is displayed as having a different sampling rate than Subj1 and Subj2, which means it is probably not related to whether the dataset was resampled or not. 
In Brainstorm, all datasets appear as correctly sampled at 1000Hz and they all have the exact same number of time points (4001).

Then when I want to create a new group study, I get the error below which I suspect may be related to this difference in Fs: 
![image](https://github.com/MIA-iEEG/mia/assets/119902277/36ff482b-d159-4d6a-a92d-c19e4092ea1e)

Could this difference in Fs come from a rounding issue when importing Brainstorm data to MIA? Else, do you have any idea where it could come from? 
Regarding the error for creating a group study, is it related to this difference in Fs? How can I fix this issue and proceed with group analysis? 

Thank you!

**Comment by annesodub** [comment]
Hi, thank you for describing in detail the problem. Yes it appears to be a rounding poroblem when calculating the sampling rate from the time vector provided by Brainstorm.. 
@rcassani : We have another question for you. MIA (re)computes the sampling rate from the 'Time' vector using this code : 

`ceil(1/mean(diff(d.Time)))`

Do you see any problem with this line? Alternatively, should I import the sampling rate from BST? 
Thank you in advance.

@avolfart : I will fix this issue asap, and yes, the difference in sampling rates prevents you from creating a group study...  

AnneSo

**Comment by rcassani** [comment]
> MIA (re)computes the sampling rate from the 'Time' vector using this code :
> 
> `ceil(1/mean(diff(d.Time)))`
>
> Do you see any problem with this line? Alternatively, should I import the sampling rate from BST?


Indeed, it seems like a rounding error. There is no need to get the sampling rate from Brainstorm. 
In Brainstorm, the sampling frequency is obtained only from the first two samples and without rounding:

`sfreq = 1 / (Time(2) - Time(1));`

The rounding in Brainstorm only happens for **printing** values of `sfreq` larger than 100 Hz

**Comment by avolfart** [comment]
Thank you for your help and very quick reply! 
@annesodub: Can you please keep me updated when it's fixed so that I can make sure I have the latest version of MIA?
Thank you in advance!

**Comment by annesodub** [comment]
Hi again, @rcassani : could you please point me at the code in Brainstorm which allow to round "for printing values of sfreq larger than 100 Hz"? (e.g. what function what line?)

Thank you.

**Comment by rcassani** [comment]
The rounding of `fs` in the Time panel happens here:
https://github.com/brainstorm-tools/brainstorm3/blob/8c494c5cef1715afd0b599614104fe7156a5131c/toolbox/gui/panel_time.m#L150-L155

**Comment by annesodub** [comment]
@avolfart : I just updated MIA such that it now uses the same computation and display of the sampling rate as Brainstorm. 

Would you please let me know if this solve the issue? (please download again mia, or from Brainstorm, Unload the plungin then press on Update (github-master).

**Comment by annesodub** [comment]
Great to hear!! 
Please do not hesitate to get in touch for anything else, it helps improving the software! thank you.
