### ISSUE TITLE
Error using mia_get_roi_permute

### ISSUE THREAD

**Issue by avolfart** [MIA-iEEG/mia#96]
Hi, 

I would like to use the function mia_get_roi_permute described in your 2022 Neuroimage paper (p. 6) to assess the significance of my inter-channel and inter-patient correlations but some of the inputs it requires are not clearly explained and I don't know what exactly I'm supposed to feed it with. 
I have sucessfully extracted the variables m_table_effect, s, smask and all_labels from my group data thanks to the "mia_get_table_effect_clc.m" script, however "mia_get_roi_permute.m" also requires variables named "t", "freqs" and "opt". 
I thought "t" might be "Time" that can be found in variable ganalysis (?) but for the other two I have no idea and I don't know where to get these variables from my data. 
Could you please help me figuring this out? 

Thanks, 
Angelique

**Comment by annesodub** [comment]
Hi Apoline,

The best description of the function calls are located in the script [MIA_script_process_companion_dataset.m](https://github.com/MIA-iEEG/mia/blob/3b54446a49c74fdbf8b3c038732a318c0f455d1c/utils/MIA_script_process_companion_dataset.m) (included in MIA)

More specifically, line 161-173 (call of the function mia_get_roi_permute with all input variables). 

As for contrasting between conditions (in case you need this), you will find an example of script in information in [mia_script_example_contrast_conditions.m](https://github.com/MIA-iEEG/mia/blob/3b54446a49c74fdbf8b3c038732a318c0f455d1c/utils/contrast/mia_script_example_contrast_conditions.m)  

Please do hesitate to re-open this issue if you have any further question.

Best,
AnneSo
